### PR TITLE
specify user

### PR DESCRIPTION
**Pull request by wahez**
Hi brot,

I wrote a patch to let you specify the username to use for the ssh session. You can type user@host in the search field. The search is done on everything after the '@' and everything before the '@' is used for the username.
I use this for a couple of host the have a default username in my .ssh/config but where I sometimes need to login as another user.

This is my first github pull request, so if I'm doing it wrong, let me know :)

cheers,
Walther

### CODE REVIEW

**Comment by brot** [comment]
Add some question/comment to your commit. Would like to know if this behaviour is intended or not.
And now that the options for a search have been extended I should document that in the README (I think a new usage section would be fine). At the moment it's not possible to add some formatted description on extension.gnome.org, so the README file would be the best place

**Comment by wahez** [comment]
Well, it was intended, but it may not be the best choice. It might clutter the search results. So I don't mind changing it to only return results if the part after '@' is not empty.

**Comment by brot** [comment]
I'm not sure about that. The string "user@" is typically for a ssh-connection. We can change this later if users are not happy with this behaviour. I will merge your changes.
Thanks for the contribution

**Comment by wahez** [comment]
Thanks for merging.
Right before I noticed your last comment, I also put some text in the README.md and implemented the other behaviour (returning no results for 'user@'). So if you want those changes let me know.

**Comment by brot** [comment]
At the moment I'm extending the README file.
But I found a problem with the "user@" search term. One of the results is always "user@" which isn't a correct ssh-connection. Could you check if you could find this problem and send a new pull request?

**Comment by brot** [comment]
I updated the README file. You can also add a pull request if you want to change something or correct some errors :-)

**Comment by wahez** [comment]
The README.md looks great.
I don't see the user@ problem. Could there be something in your .ssh/config or known_host that ends up as a empty hostname in the search provider?

**Comment by brot** [comment]
Ok, I found the "user@" problem. I have to trim the file-content before split them into the lines.
I uploaded the new version to extensions.gnome.org. Someone had to review this version and then it will be available for download.
Additionally I add an icon and a screenshot on extensions.gnome.org

**Pull request merged**
